In [ ]:
import pandas as pd
data = pd.read_csv('data.csv', delimiter=';')

In [ ]:
data

,DATAFLOW,ACTION,MEASURE,REF_AREA,ACTIVITY,COUNTERPART_AREA,UNIT_MEASURE,FREQ,TIME_PERIOD,OBS_VALUE,UNIT_MULT,CONTACT,DATA_COMP,STAT_CONC_DEF
0,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,A03,W,USD,A,2008,13729.5,6,[object Object],[object Object],NaN
1,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,A03,W,USD,A,2008,4492.5,6,[object Object],[object Object],NaN
2,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,B05_06,W,USD,A,2008,42761.8,6,[object Object],[object Object],NaN
3,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,B05_06,W,USD,A,2008,418764.0,6,[object Object],[object Object],NaN
4,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,B07_08,W,USD,A,2008,14827.7,6,[object Object],[object Object],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2767,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,GTT,W,USD,A,2019,27416625.2,6,[object Object],[object Object],NaN
2768,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,JTN,W,USD,A,2019,840270.5,6,[object Object],[object Object],NaN
2769,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,JTN,W,USD,A,2019,13235123.6,6,[object Object],[object Object],NaN
2770,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,INFO,W,USD,A,2019,294784.5,6,[object Object],[object Object],NaN
2771,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,INFO,W,USD,A,2019,2832264.7,6,[object Object],[object Object],NaN

In [ ]:
filtered_df = data[data['ACTIVITY'] == '_T']

,DATAFLOW,ACTION,MEASURE,REF_AREA,ACTIVITY,COUNTERPART_AREA,UNIT_MEASURE,FREQ,TIME_PERIOD,OBS_VALUE,UNIT_MULT,CONTACT,DATA_COMP,STAT_CONC_DEF
88,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2008,2874471.0,6,[object Object],[object Object],NaN
89,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2008,26501561.2,6,[object Object],[object Object],NaN
220,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2004,1542772.9,6,[object Object],[object Object],NaN
221,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2004,21246557.4,6,[object Object],[object Object],NaN
352,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2016,4040714.7,6,[object Object],[object Object],NaN
353,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2016,32186630.1,6,[object Object],[object Object],NaN
484,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2000,1030000.2,6,[object Object],[object Object],NaN
485,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2000,18258296.1,6,[object Object],[object Object],NaN
616,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2012,3605634.8,6,[object Object],[object Object],NaN
617,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2012,28649988.8,6,[object Object],[object Object],NaN
748,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2020,4839598.5,6,[object Object],[object Object],NaN
749,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2020,35844816.2,6,[object Object],[object Object],NaN
880,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2001,1067607.8,6,[object Object],[object Object],NaN
881,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2001,18523035.7,6,[object Object],[object Object],NaN
1012,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2005,1826112.1,6,[object Object],[object Object],NaN
1013,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2005,23043042.0,6,[object Object],[object Object],NaN
1144,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2009,2982314.4,6,[object Object],[object Object],NaN
1145,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2009,24483111.8,6,[object Object],[object Object],NaN
1276,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2013,3699343.5,6,[object Object],[object Object],NaN
1277,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2013,29740179.8,6,[object Object],[object Object],NaN
1408,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2017,4563163.5,6,[object Object],[object Object],NaN
1409,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2017,33693874.9,6,[object Object],[object Object],NaN
1540,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2002,1116117.6,6,[object Object],[object Object],NaN
1541,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2002,18787212.1,6,[object Object],[object Object],NaN
1672,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2006,2074954.4,6,[object Object],[object Object],NaN
1673,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2006,24413184.2,6,[object Object],[object Object],NaN
1804,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2010,3721354.9,6,[object Object],[object Object],NaN
1805,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2010,25966571.9,6,[object Object],[object Object],NaN
1936,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2014,3916743.5,6,[object Object],[object Object],NaN
1937,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2014,31112499.6,6,[object Object],[object Object],NaN
2068,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2018,4921477.2,6,[object Object],[object Object],NaN
2069,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2018,35723718.7,6,[object Object],[object Object],NaN
2200,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2003,1291606.5,6,[object Object],[object Object],NaN
2201,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2003,19732985.8,6,[object Object],[object Object],NaN
2332,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2007,2626371.6,6,[object Object],[object Object],NaN
2333,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2007,25727016.8,6,[object Object],[object Object],NaN
2464,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2011,3786939.4,6,[object Object],[object Object],NaN
2465,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2011,27501394.8,6,[object Object],[object Object],NaN
2596,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2015,3912030.3,6,[object Object],[object Object],NaN
2597,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2015,31520999.2,6,[object Object],[object Object],NaN
2728,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,IND,_T,W,USD,A,2019,5100167.1,6,[object Object],[object Object],NaN
2729,OECD.STI.PIE:DSD_TIVA_MAINLV@DF_MAINLV(1.0),I,PROD,USA,_T,W,USD,A,2019,36918681.2,6,[object Object],[object Object],NaN

In [ ]:
def calculate_activity_share(df):
    # Group by TIME_PERIOD, REF_AREA, and ACTIVITY
    grouped = df.groupby(['TIME_PERIOD', 'REF_AREA'])

    # Define a lambda function to calculate the share for each activity
    def get_share(group):
        total_value = group[group['ACTIVITY'] == '_T']['OBS_VALUE'].values[0]  # Get the total value for each group
        group['SHARE'] = group['OBS_VALUE'] / total_value  # Calculate the share for each activity
        return group

    # Apply the function to each group
    result_df = grouped.apply(get_share)

    # Filter out the total rows (_T) as we only need the share for individual activities
    result_df = result_df[result_df['ACTIVITY'] != '_T']

    # Select relevant columns for the output
    output_df = result_df[['ACTIVITY', 'TIME_PERIOD', 'REF_AREA', 'SHARE']]

    return output_df

In [ ]:
data_gen = calculate_activity_share(data)

<ipython-input-11-21fca0849dde>:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  result_df = grouped.apply(get_share)

In [ ]:
data_gen

                         ACTIVITY  TIME_PERIOD REF_AREA     SHARE
TIME_PERIOD REF_AREA
2000        IND      396      A03         2000      IND  0.006626
                     398   B05_06         2000      IND  0.014580
                     400   B07_08         2000      IND  0.002418
                     402      B09         2000      IND  0.002554
                     404   C10T12         2000      IND  0.046611
...                           ...          ...      ...       ...
2020        USA      783      RTT         2020      USA  0.020427
                     785      R_S         2020      USA  0.019800
                     787      GTT         2020      USA  0.753375
                     789      JTN         2020      USA  0.374765
                     791     INFO         2020      USA  0.082091

[2730 rows x 4 columns]

In [ ]:
data_gen.to_csv('gen_data.csv')

In [ ]:
data_x = data_gen.reset_index(drop=True)

In [ ]:
data_x

     ACTIVITY  TIME_PERIOD REF_AREA     SHARE
0         A03         2000      IND  0.006626
1      B05_06         2000      IND  0.014580
2      B07_08         2000      IND  0.002418
3         B09         2000      IND  0.002554
4      C10T12         2000      IND  0.046611
...       ...          ...      ...       ...
2725      RTT         2020      USA  0.020427
2726      R_S         2020      USA  0.019800
2727      GTT         2020      USA  0.753375
2728      JTN         2020      USA  0.374765
2729     INFO         2020      USA  0.082091

[2730 rows x 4 columns]

In [ ]:
data_x.to_csv('data_x.csv')

In [ ]:
multiplier = pd.read_csv('multiply_data.csv')

In [ ]:
multiplier_focuss = multiplier[['REF_AREA', 'OBS_VALUE', 'TIME_PERIOD', 'Institutional sector', 'ACTIVITY']]

In [ ]:
multiplier_focuss = multiplier_focuss[multiplier_focuss['Institutional sector']=='Total economy']

In [ ]:
multiplier_focuss = multiplier_focuss[multiplier_focuss['ACTIVITY']=='_T']

In [ ]:
multiplier_focuss.to_csv('multiplier_focus.csv')

In [ ]:
multiplier_focuss

    REF_AREA   OBS_VALUE  TIME_PERIOD Institutional sector ACTIVITY
1        IND   59.915847         2006        Total economy       _T
2        IND   57.086020         2005        Total economy       _T
4        IND   93.966402         2017        Total economy       _T
5        IND   91.276104         2016        Total economy       _T
6        IND   91.199404         2015        Total economy       _T
7        IND   79.096690         2011        Total economy       _T
8        IND   74.487720         2010        Total economy       _T
9        IND   70.597374         2009        Total economy       _T
10       IND   67.375763         2008        Total economy       _T
19       IND   91.610751         2014        Total economy       _T
20       IND  100.000000         2020        Total economy       _T
21       IND   87.472331         2013        Total economy       _T
22       IND   83.803483         2012        Total economy       _T
23       IND   49.460818         2003        Total economy       _T
24       IND   47.911583         2002        Total economy       _T
25       IND   47.123537         2001        Total economy       _T
26       IND   44.446005         2000        Total economy       _T
27       IND   99.669367         2019        Total economy       _T
28       IND   53.468826         2004        Total economy       _T
63       IND   62.974960         2007        Total economy       _T
103      USA   84.021490         2005        Total economy       _T
104      USA   80.557350         2004        Total economy       _T
105      USA   78.240435         2003        Total economy       _T
106      USA   77.503808         2002        Total economy       _T
107      USA   93.680430         2014        Total economy       _T
108      USA   92.003251         2013        Total economy       _T
109      USA   91.071825         2012        Total economy       _T
110      USA   89.732182         2011        Total economy       _T
111      USA   88.524536         2010        Total economy       _T
112      USA   89.448162         2009        Total economy       _T
113      USA   90.116802         2008        Total economy       _T
114      USA   88.931476         2007        Total economy       _T
115      USA   87.096943         2006        Total economy       _T
116      USA   76.419130         2001        Total economy       _T
117      USA   75.299413         2000        Total economy       _T
118      USA  100.000000         2020        Total economy       _T
119      USA   98.858875         2019        Total economy       _T
120      USA   97.419159         2018        Total economy       _T
121      USA   95.741994         2017        Total economy       _T
122      USA   94.315156         2016        Total economy       _T
123      USA   94.280226         2015        Total economy       _T
136      IND   97.629251         2018        Total economy       _T

In [ ]:
def multiply_share_with_obs_value(df1, df2):
    # Merge the dataframes on 'TIME_PERIOD' and 'REF_AREA'
    merged_df = pd.merge(df1, df2, on=['TIME_PERIOD', 'REF_AREA'], how='left')

    # Multiply 'OBS_VALUE' from df2 with 'SHARE' from df1 for each row
    merged_df['RESULT'] = merged_df['OBS_VALUE'] * merged_df['SHARE']

    return merged_df

In [ ]:
step_one_data = multiply_share_with_obs_value(data_x, multiplier_focuss)

In [ ]:
step_one_data

,ACTIVITY_x,TIME_PERIOD,REF_AREA,SHARE,OBS_VALUE,Institutional sector,ACTIVITY_y,RESULT
0,A03,2000,IND,0.006626,44.446005,Total economy,_T,0.294491
1,B05_06,2000,IND,0.014580,44.446005,Total economy,_T,0.648044
2,B07_08,2000,IND,0.002418,44.446005,Total economy,_T,0.107473
3,B09,2000,IND,0.002554,44.446005,Total economy,_T,0.113506
4,C10T12,2000,IND,0.046611,44.446005,Total economy,_T,2.071684
...,...,...,...,...,...,...,...,...
2725,RTT,2020,USA,0.020427,100.000000,Total economy,_T,2.042717
2726,R_S,2020,USA,0.019800,100.000000,Total economy,_T,1.980025
2727,GTT,2020,USA,0.753375,100.000000,Total economy,_T,75.337487
2728,JTN,2020,USA,0.374765,100.000000,Total economy,_T,37.476505
2729,INFO,2020,USA,0.082091,100.000000,Total economy,_T,8.209051

In [ ]:
data_step_one = step_one_data.drop(columns=['Institutional sector', 'ACTIVITY_y'])

In [ ]:
data_step_one

     ACTIVITY_x  TIME_PERIOD REF_AREA     SHARE   OBS_VALUE     RESULT
0           A03         2000      IND  0.006626   44.446005   0.294491
1        B05_06         2000      IND  0.014580   44.446005   0.648044
2        B07_08         2000      IND  0.002418   44.446005   0.107473
3           B09         2000      IND  0.002554   44.446005   0.113506
4        C10T12         2000      IND  0.046611   44.446005   2.071684
...         ...          ...      ...       ...         ...        ...
2725        RTT         2020      USA  0.020427  100.000000   2.042717
2726        R_S         2020      USA  0.019800  100.000000   1.980025
2727        GTT         2020      USA  0.753375  100.000000  75.337487
2728        JTN         2020      USA  0.374765  100.000000  37.476505
2729       INFO         2020      USA  0.082091  100.000000   8.209051

[2730 rows x 6 columns]

In [ ]:
data_step_one.to_csv('data_step_one.csv')

In [ ]:
def calculate_result_ratio(df):
    # Filter the DataFrame for IND and USA
    df_ind = df[df['REF_AREA'] == 'IND']
    df_usa = df[df['REF_AREA'] == 'USA']

    # Merge IND and USA data on TIME_PERIOD and ACTIVITY_x
    merged_df = pd.merge(
        df_ind, df_usa,
        on=['TIME_PERIOD', 'ACTIVITY_x'],
        suffixes=('_IND', '_USA')
    )

    # Calculate the ratio
    merged_df['RESULT_RATIO'] = merged_df['RESULT_IND'] / merged_df['RESULT_USA']

    # Select relevant columns and drop REF_AREA
    result_df = merged_df[['TIME_PERIOD', 'ACTIVITY_x', 'RESULT_RATIO']]

    return result_df

In [ ]:
data_step_two = calculate_result_ratio(data_step_one)

In [ ]:
data_step_two

      TIME_PERIOD ACTIVITY_x  RESULT_RATIO
0            2000        A03     20.532256
1            2000     B05_06      0.977219
2            2000     B07_08      0.844225
3            2000        B09      1.320556
4            2000     C10T12      0.923943
...           ...        ...           ...
1360         2020        RTT      0.736984
1361         2020        R_S      0.720671
1362         2020        GTT      0.551202
1363         2020        JTN      0.441367
1364         2020       INFO      0.704481

[1365 rows x 3 columns]

In [ ]:
data_step_two.to_csv('data_step_two.csv')

In [ ]:
last_df = pd.read_csv('/content/exchange_rate_india_US.csv')

In [ ]:
last_df.rename(columns={"Unnamed: 0": "YEAR", "N534XUSB@G10": "RATE"}, inplace=True)

In [ ]:
last_df

       YEAR                                               RATE
0     .desc           Foreign Exchange Rate: India (Rupee/US$)
1   .source              Federal Reserve Board/Haver Analytics
2     .dtlm  Tue Dec 03 2024 08:08:10 GMT+0530 (India Stand...
3      .frq                                               Year
4      1970                                             7.5658
5      1971                                             7.5251
6      1972                                             7.5945
7      1973                                              7.742
8      1974                                             8.1016
9      1975                                             8.3759
10     1976                                             8.9604
11     1977                                             8.7386
12     1978                                             8.1928
13     1979                                             8.1258
14     1980                                             7.8629
15     1981                                             8.6585
16     1982                                             9.4551
17     1983                                            10.0989
18     1984                                            11.3626
19     1985                                            12.3687
20     1986                                            12.6108
21     1987                                            12.9586
22     1988                                            13.9028
23     1989                                            16.2071
24     1990                                            17.5021
25     1991                                            22.7199
26     1992                                            28.1353
27     1993                                             31.257
28     1994                                            31.3943
29     1995                                            32.4323
30     1996                                            35.5166
31     1997                                            36.3647
32     1998                                            41.3293
33     1999                                            43.1217
34     2000                                            45.0009
35     2001                                            47.2241
36     2002                                             48.622
37     2003                                            46.5947
38     2004                                            45.2763
39     2005                                            44.0113
40     2006                                            45.1722
41     2007                                            41.1969
42     2008                                            43.4114
43     2009                                            48.3195
44     2010                                            45.6493
45     2011                                            46.6122
46     2012                                            53.3591
47     2013                                            58.5255
48     2014                                            61.0174
49     2015                                            64.1029
50     2016                                            67.1668
51     2017                                            65.1015
52     2018                                            68.4018
53     2019                                            70.4041
54     2020                                            74.1103
55     2021                                            73.9267
56     2022                                            78.5766
57     2023                                            82.5728

In [ ]:
last_df = last_df.drop([0, 1, 2, 3])

In [ ]:
last_df['YEAR'] = last_df['YEAR'].apply(lambda x: float(x))

In [ ]:
merged_df = pd.merge(data_step_two, last_df, left_on='TIME_PERIOD', right_on='YEAR', how='left')

In [ ]:
merged_df

      TIME_PERIOD ACTIVITY_x  RESULT_RATIO    YEAR     RATE
0            2000        A03     20.532256  2000.0  45.0009
1            2000     B05_06      0.977219  2000.0  45.0009
2            2000     B07_08      0.844225  2000.0  45.0009
3            2000        B09      1.320556  2000.0  45.0009
4            2000     C10T12      0.923943  2000.0  45.0009
...           ...        ...           ...     ...      ...
1360         2020        RTT      0.736984  2020.0  74.1103
1361         2020        R_S      0.720671  2020.0  74.1103
1362         2020        GTT      0.551202  2020.0  74.1103
1363         2020        JTN      0.441367  2020.0  74.1103
1364         2020       INFO      0.704481  2020.0  74.1103

[1365 rows x 5 columns]

In [ ]:
print(merged_df.dtypes)

TIME_PERIOD       int64
ACTIVITY_x       object
RESULT_RATIO    float64
YEAR            float64
RATE             object
dtype: object

In [ ]:
merged_df['RATE'] = pd.to_numeric(merged_df['RATE'], errors='coerce')

In [ ]:
merged_df

      TIME_PERIOD ACTIVITY_x  RESULT_RATIO    YEAR     RATE
0            2000        A03     20.532256  2000.0  45.0009
1            2000     B05_06      0.977219  2000.0  45.0009
2            2000     B07_08      0.844225  2000.0  45.0009
3            2000        B09      1.320556  2000.0  45.0009
4            2000     C10T12      0.923943  2000.0  45.0009
...           ...        ...           ...     ...      ...
1360         2020        RTT      0.736984  2020.0  74.1103
1361         2020        R_S      0.720671  2020.0  74.1103
1362         2020        GTT      0.551202  2020.0  74.1103
1363         2020        JTN      0.441367  2020.0  74.1103
1364         2020       INFO      0.704481  2020.0  74.1103

[1365 rows x 5 columns]

In [ ]:
merged_df['RESULT_RATIO_RATE'] = merged_df['RESULT_RATIO'] * merged_df['RATE']

In [ ]:
final_final_df = merged_df[['TIME_PERIOD', 'ACTIVITY_x', 'RESULT_RATIO', 'RESULT_RATIO_RATE', 'RATE']]

In [ ]:
final_final_df

      TIME_PERIOD ACTIVITY_x  RESULT_RATIO  RESULT_RATIO_RATE     RATE
0            2000        A03     20.532256         923.970004  45.0009
1            2000     B05_06      0.977219          43.975727  45.0009
2            2000     B07_08      0.844225          37.990880  45.0009
3            2000        B09      1.320556          59.426219  45.0009
4            2000     C10T12      0.923943          41.578285  45.0009
...           ...        ...           ...                ...      ...
1360         2020        RTT      0.736984          54.618092  74.1103
1361         2020        R_S      0.720671          53.409149  74.1103
1362         2020        GTT      0.551202          40.849713  74.1103
1363         2020        JTN      0.441367          32.709821  74.1103
1364         2020       INFO      0.704481          52.209297  74.1103

[1365 rows x 5 columns]

In [ ]:
final_final_df.to_csv('final_final_df.csv')

In [ ]:
'''

I have one df which has TIME_PERIOD ACTIVITY_x RESULT_RATIO
I have another df which YEAR RATE


for all the rows in the first df where TIME_PERIOD == YEAR multiple RESULT_RATIO with RATE

the output df should have TIME_PERIOD ACTIVITY_x RESULT_RATIO RESULT_RATIO_RATE and RATE


python function

'''

In [ ]:
def calculate_result_ratio_rate(df1, df2):
    # Merge df1 and df2 based on TIME_PERIOD and YEAR
    merged_df = pd.merge(df1, df2, left_on='TIME_PERIOD', right_on='YEAR', how='left')

    # Calculate RESULT_RATIO_RATE
    merged_df['RESULT_RATIO_RATE'] = merged_df['RESULT_RATIO'] * merged_df['RATE']

    # Select and reorder columns
    output_df = merged_df[['TIME_PERIOD', 'ACTIVITY_x', 'RESULT_RATIO', 'RESULT_RATIO_RATE', 'RATE']]

    return output_df

In [ ]:
final_df = calculate_result_ratio_rate(data_step_two, last_df)

TypeError: can't multiply sequence by non-int of type 'float'